<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>

<!DOCTYPE repertoire [
<!-- Racine -->

<!ELEMENT repertoire (personne*)>


<!-- Personne -->

<!ELEMENT personne (nom, prenom, adresse, telephones, emails)>

<!ATTLIST personne sexe (masculin | feminin) #REQUIRED>


<!-- Nom et prénom -->

<!ELEMENT nom (#PCDATA)>

<!ELEMENT prenom (#PCDATA)>


<!-- Bloc adresse -->

<!ELEMENT adresse (numero, voie, codePostal, ville, pays)>

<!ELEMENT numero (#PCDATA)>


<!ELEMENT voie (#PCDATA)>

<!ATTLIST voie type CDATA #REQUIRED>


<!ELEMENT codePostal (#PCDATA)>

<!ELEMENT ville (#PCDATA)>

<!ELEMENT pays (#PCDATA)>


<!-- Bloc téléphone -->

<!ELEMENT telephones (telephone+)>

<!ELEMENT telephone (#PCDATA)>

<!ATTLIST telephone type CDATA #REQUIRED>


<!-- Bloc email -->

<!ELEMENT emails (email+)>

<!ELEMENT email (#PCDATA)>

<!ATTLIST email type CDATA #REQUIRED>

]>
<repertoire>

    <!-- John DOE -->

    <personne sexe="masculin">

        <nom>DOE</nom>

        <prenom>John</prenom>

        <adresse>

            <numero>7</numero>

            <voie type="impasse">impasse du chemin</voie>

            <codePostal>75015</codePostal>

            <ville>PARIS</ville>

            <pays>FRANCE</pays>

        </adresse>

        <telephones>

            <telephone type="fixe">01 02 03 04 05</telephone>

            <telephone type="portable">06 07 08 09 10</telephone>

        </telephones>

        <emails>

            <email type="personnel">john.doe@wanadoo.fr</email>

            <email type="professionnel">john.doe@societe.com</email>

        </emails>

    </personne>

    

    <!-- Marie POPPINS -->

    <personne sexe="feminin">

        <nom>POPPINS</nom>

        <prenom>Marie</prenom>

        <adresse>

            <numero>28</numero>

            <voie type="avenue">avenue de la république</voie>

            <codePostal>13005</codePostal>

            <ville>MARSEILLE</ville>

            <pays>FRANCE</pays>

        </adresse>

        <telephones>

            <telephone type="bureau">04 05 06 07 08</telephone>

        </telephones>

        <emails>

            <email type="professionnel">contact@poppins.fr</email>

        </emails>

    </personne>

</repertoire>

